# Default values for jx-node-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

knativeDeploy: false
draft: {}

replicaCount: 1

image:
  repository: draft
  tag: dev
  pullPolicy: "IfNotPresent"

podAnnotations: {}

env: {}

postgresql:
  image:
    tag: 10-debian-9
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: jxapp
  persistence:
    enabled: false

service:
  name: jx-node-app-svc
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
  type: ClusterIP

resources:1`
  limits:
    cpu: "50m"
    memory: "100Mi"

probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

terminationGracePeriodSeconds: 10
